### ISSUE TITLE
sbt run fails with java.lang.NumberFormatException: Not a version: 11

### ISSUE THREAD

**Issue by gabrimonfa** [italia/daf-semantic-validator#1]
ubuntu 19.04.
Following README I issued "sbt clean package" and then "sbt run"

"sbt run" gives the following error

```bash
$ sbt run
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.valueOf(Integer.java:983)
        at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
        at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
        at jline.UnixTerminal.<init>(UnixTerminal.java:65)
        at jline.UnixTerminal.<init>(UnixTerminal.java:50)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
        at jline.TerminalFactory.create(TerminalFactory.java:102)
        at jline.TerminalFactory.get(TerminalFactory.java:186)
        at jline.TerminalFactory.get(TerminalFactory.java:192)
        at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:123)
        at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:117)
        at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
        at sbt.GlobalLogging$.initial(GlobalLogging.scala:43)
        at sbt.StandardMain$.initialGlobalLogging(Main.scala:116)
        at sbt.StandardMain$.initialState(Main.scala:125)
        at sbt.xMain.run(Main.scala:34)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:119)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)

[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /home/user/daf-semantic-validator/project
[info] Set current project to semantic_validator (in build file:/home/user/daf-semantic-validator/)

java.lang.NumberFormatException: Not a version: 11
        at scala.util.PropertiesTrait$class.parts$1(Properties.scala:176)
        at scala.util.PropertiesTrait$class.isJavaAtLeast(Properties.scala:180)
        at scala.util.Properties$.isJavaAtLeast(Properties.scala:16)
        at play.runsupport.FileWatchService$$anon$1.delegate$lzycompute(FileWatchService.scala:78)
        at play.runsupport.FileWatchService$$anon$1.delegate(FileWatchService.scala:76)
        at play.runsupport.FileWatchService$$anon$1.watch(FileWatchService.scala:89)
        at play.runsupport.Reloader.<init>(Reloader.scala:310)
        at play.runsupport.Reloader$.reloader$lzycompute$1(Reloader.scala:210)
        at play.runsupport.Reloader$.play$runsupport$Reloader$$reloader$1(Reloader.scala:210)
        at play.runsupport.Reloader$.startDevMode(Reloader.scala:234)
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run 'last compile:run' for the full output.
[error] (compile:run) java.lang.NumberFormatException: Not a version: 11
[error] Total time: 0 s, completed 5 nov 2019, 10:48:18
```

**Comment by gabrimonfa** [comment]
Solved. It needs Java 8, not 11

**Comment by jayaganesh45** [comment]
How did you change the java version??

**Comment by dr0i** [comment]
@jayaganesh45 try e.g. `$ sbt -java-home /usr/lib/jvm/jdk1.8.0_144/` if setting like `export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_144/` is not sufficient (as it is in my case).
